In [81]:
import pandas as pd
import numpy as np

Upload the csv file

In [82]:
df = pd.read_csv('/Users/rosenrot/Downloads/Information.csv')

View  the csv Data

In [83]:
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,Entity,alternative name,story,YEAR,records lost,ORGANISATION,METHOD OF LEAK,interesting story,NO OF RECORDS STOLEN,DATA SENSITIVITY,UNUSED,UNUSED,Exclude,NaN,1st source link,2nd source link,3rd source,source name
1,NaN,NaN,Elaboration if there's an interesting story or...,"years are encoded (0=2004, 8 = 2012, 9 = 2013,...","(use 3m, 4m, 5m or 10m to approximate unknown ...",NaN,NaN,NaN,"(use 3m, 4m, 5m or 10m to approximate unknown ...",1. Just email address/Online information 20 SS...,NaN,NaN,Show this item in the viz?,NaN,NaN,NaN,NaN,NaN
2,AOL,American Online,A former America Online software engineer stol...,0,92000000,web,inside job,NaN,92000000,1,NaN,NaN,NaN,NaN,http://money.cnn.com/2004/06/23/technology/aol...,http://www.msnbc.msn.com/id/8985989/#.UFcN8RgUwaA,NaN,CNN
3,Automatic Data Processing,"Business outsourcing, payrolls, benefits",NaN,1,125000,financial,poor security,NaN,130000,20,NaN,NaN,NaN,NaN,http://abcnews.go.com/Technology/story?id=2160...,NaN,NaN,ABC
4,Ameritrade Inc.,Computer backup tape containing personal infor...,online broker,1,200000,financial,lost / stolen device,NaN,200000,20,NaN,NaN,NaN,NaN,http://www.nbcnews.com/id/7561268/,NaN,NaN,NaN

Drop the colums that are not required

In [ ]:
df.drop(['Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17'], axis =1,inplace=True)

View the columns again

In [85]:
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Entity,alternative name,story,YEAR,records lost,ORGANISATION,METHOD OF LEAK,interesting story,NO OF RECORDS STOLEN,DATA SENSITIVITY
1,NaN,NaN,Elaboration if there's an interesting story or...,"years are encoded (0=2004, 8 = 2012, 9 = 2013,...","(use 3m, 4m, 5m or 10m to approximate unknown ...",NaN,NaN,NaN,"(use 3m, 4m, 5m or 10m to approximate unknown ...",1. Just email address/Online information 20 SS...
2,AOL,American Online,A former America Online software engineer stol...,0,92000000,web,inside job,NaN,92000000,1
3,Automatic Data Processing,"Business outsourcing, payrolls, benefits",NaN,1,125000,financial,poor security,NaN,130000,20
4,Ameritrade Inc.,Computer backup tape containing personal infor...,online broker,1,200000,financial,lost / stolen device,NaN,200000,20

View the index

In [88]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'],
      dtype='object')

Rename the columns

In [89]:
Column_Names=df.iloc[0].values.tolist()
df.columns=Column_Names
df.head()

,Entity,alternative name,story,YEAR,records lost,ORGANISATION,METHOD OF LEAK,interesting story,NO OF RECORDS STOLEN,DATA SENSITIVITY
0,Entity,alternative name,story,YEAR,records lost,ORGANISATION,METHOD OF LEAK,interesting story,NO OF RECORDS STOLEN,DATA SENSITIVITY
1,NaN,NaN,Elaboration if there's an interesting story or...,"years are encoded (0=2004, 8 = 2012, 9 = 2013,...","(use 3m, 4m, 5m or 10m to approximate unknown ...",NaN,NaN,NaN,"(use 3m, 4m, 5m or 10m to approximate unknown ...",1. Just email address/Online information 20 SS...
2,AOL,American Online,A former America Online software engineer stol...,0,92000000,web,inside job,NaN,92000000,1
3,Automatic Data Processing,"Business outsourcing, payrolls, benefits",NaN,1,125000,financial,poor security,NaN,130000,20
4,Ameritrade Inc.,Computer backup tape containing personal infor...,online broker,1,200000,financial,lost / stolen device,NaN,200000,20

Make the location 0 as the main index

In [93]:
df.iloc[0].drop

<bound method NDFrame.drop of Entity                                Entity
alternative name            alternative name
story                                  story
YEAR                                    YEAR
records lost                    records lost
ORGANISATION                    ORGANISATION
METHOD OF LEAK                METHOD OF LEAK
interesting story          interesting story
NO OF RECORDS STOLEN    NO OF RECORDS STOLEN
DATA SENSITIVITY            DATA SENSITIVITY
Name: 0, dtype: object>

In [ ]:
Drop the column 0

In [95]:
df.drop(0,inplace=True)

In [96]:
df.head()

,Entity,alternative name,story,YEAR,records lost,ORGANISATION,METHOD OF LEAK,interesting story,NO OF RECORDS STOLEN,DATA SENSITIVITY
1,NaN,NaN,Elaboration if there's an interesting story or...,"years are encoded (0=2004, 8 = 2012, 9 = 2013,...","(use 3m, 4m, 5m or 10m to approximate unknown ...",NaN,NaN,NaN,"(use 3m, 4m, 5m or 10m to approximate unknown ...",1. Just email address/Online information 20 SS...
2,AOL,American Online,A former America Online software engineer stol...,0,92000000,web,inside job,NaN,92000000,1
3,Automatic Data Processing,"Business outsourcing, payrolls, benefits",NaN,1,125000,financial,poor security,NaN,130000,20
4,Ameritrade Inc.,Computer backup tape containing personal infor...,online broker,1,200000,financial,lost / stolen device,NaN,200000,20
5,Citigroup,NaN,Blame the messenger! A box of computer tapes c...,1,3900000,financial,lost / stolen device,y,3900000,300

In [24]:
df['alternative name'].isnull().count()

254

In [36]:
len(np.where(df['alternative name'].isnull())[0])

136

In [37]:
len(np.where(df['story'].isnull())[0])

36

In [38]:
len(np.where(df['YEAR'].isnull())[0])

0

In [39]:
len(np.where(df['records lost'].isnull())[0])

2

In [40]:
np.where(df['records lost'].isnull())[0]

array([147, 163])

In [42]:

df.drop(1,inplace=True)

In [43]:
df

,Entity,alternative name,story,YEAR,records lost,ORGANISATION,METHOD OF LEAK,interesting story,NO OF RECORDS STOLEN,DATA SENSITIVITY
2,AOL,American Online,A former America Online software engineer stol...,0,92000000,web,inside job,NaN,92000000,1
3,Automatic Data Processing,"Business outsourcing, payrolls, benefits",NaN,1,125000,financial,poor security,NaN,130000,20
4,Ameritrade Inc.,Computer backup tape containing personal infor...,online broker,1,200000,financial,lost / stolen device,NaN,200000,20
5,Citigroup,NaN,Blame the messenger! A box of computer tapes c...,1,3900000,financial,lost / stolen device,y,3900000,300
6,Cardsystems Solutions Inc.,"Third-party payment processor for Visa, Master...",CardSystems was fingered by MasterCard after i...,1,40000000,financial,hacked,y,40000000,300
7,Hewlett Packard,NaN,Laptop lost/stolen containing employee data: n...,2,200000,"tech, retail",lost / stolen device,y,200000,20
8,Countrywide Financial Corp,Mortgage financer,NaN,2,2600000,financial,inside job,NaN,2600000,300
9,KDDI,Japanese telecommunications operator,"Press report: ""Tokyo police have arrested two ...",2,4000000,telecoms,hacked,y,4000000,1
10,"T-Mobile, Deutsche Telecom",NaN,Thieves got their hands on a storage device wi...,2,17000000,telecoms,lost / stolen device,NaN,17000000,1
11,AOL,American Online,Durp. AOL VOLUNTARILY released search data for...,2,20000000,web,accidentally published,y,20000000,1
12,US Dept of Vet Affairs,NaN,The Veterans Affairs Department agreed to pay ...,2,26500000,"government, military",lost / stolen device,NaN,26500000,20
13,Texas Lottery,NaN,"Data on more than 89,000 lottery winners (incl...",3,89000,government,inside job,NaN,90000,20
14,City and Hackney Teaching Primary Care Trust,NaN,Heavily encrypted disks containing details of ...,3,160000,government,lost / stolen device,NaN,160000,20
15,Gap Inc,NaN,Stolen laptop which contained social security ...,3,800000,retail,lost / stolen device,NaN,800000,20
16,Compass Bank,NaN,A former employee stole a hardrive containing ...,3,1000000,financial,inside job,y,1000000,300
17,Monster.com,Jobs website,A trojan virus stole log-ins that were used to...,3,1600000,web,hacked,y,1600000,20
18,Driving Standards Agency,NaN,Hard disk with details of candidates for the d...,3,3000000,government,lost / stolen device,NaN,3000000,20
19,"Driving Standards Agency,",Details of candidates for the driving theory t...,NaN,3,3000000,government,lost / stolen device,NaN,3000000,20
20,Hannaford Brothers Supermarket Chain,"Delhaize Group: Hannaford Bros, Sweetbay, Food...",An estimated 4.2 million credit and debit card...,3,4200000,retail,hacked,NaN,4200000,300
21,TD Ameritrade,US online broker,TD Ameritrade settled a class action lawsuit t...,3,6300000,financial,hacked,NaN,6300000,1
22,Fidelity National Information Services,Employee sold customer information to a data b...,NaN,3,8500000,financial,inside job,NaN,8500000,300
23,Dai Nippon Printing,Japanese printing company,A former contractor of Dai Nippon Printing Com...,3,8637405,retail,inside job,NaN,8600000,1
24,UK Revenue & Customs,HMRC,A set of discs containing confidential details...,3,25000000,government,lost / stolen device,NaN,25000000,1
25,TK / TJ Maxx,Largest retail breach to date,Hackers hacked a Minnesota store wifi network ...,3,94000000,retail,hacked,NaN,94000000,300
26,Service Personnel and Veterans Agency (UK),NaN,Stolen USBs containing personal information ab...,4,50500,government,lost / stolen device,NaN,50000,20
27,Stanford University,NaN,Tens of thousands of past and current Stanford...,4,72000,academic,lost / stolen device,NaN,72000,20
28,UK Home Office,NaN,PA Consulting lost an unencrypted memory stick...,4,84000,government,lost / stolen device,NaN,84000,20
29,AT&T,NaN,A laptop was stolen from a car containing unen...,4,113000,telecoms,lost / stolen device,y,100000,1
30,Starbucks,NaN,A laptop was stolen that contained private inf...,4,97000,retail,lost / stolen device,y,100000,20
31,RBS Worldpay,the U.S. payment processing arm of The Royal B...,The hack primarily effected U.S. prepaid and t...,4,1500000,financial,hacked,NaN,1500000,20
...,...,...,...,...,...,...,...,...,...,...
225,uTorrent,NaN,"It's unclear what data has been breached, exac...",12,35000,web,hacked,NaN,35000,1
226,Banner Health,NaN,Hackers gained access to payment card data via...,12,3700000,healthcare,hacked,NaN,3700000,300
227,Privatization Agency of the Republic of Serbia,NaN,A text file with personal data and financial d...,12,5190396,government,accidentally published,NaN,519396,20
228,Quest Diagnostics,NaN,"Nov. The stolen data contained names, DOBs, la...",13,34000,healthcare,hacked,NaN,34000,4000
229,Three,Three mobile company in the UK,Hackers broke into Three's customer database w...,13,200000,telecoms,hacked,NaN,200000,20
230,Wonga,NaN,Apr. Customers from the UK and Poland look to ...,13,270000,financial,hacked,NaN,270000,50000
231,PayAsUGym,NaN,Dec. Fitness website hacked & email address pu...,13,300000,web,hacked,NaN,300000,1
232,Red Cross Blood Service,NaN,Info leaked includes data about 'at risk sexua...,13,550000,healthcare,accidentally published,NaN,550000,4000
233,DaFont,Font sharing site,May. Apparently the hacker found out others we...,13,700000,web,hacked,NaN,700000,4000
234,Brazzers,Porn site,"Sept. 'The data contains 790,724 unique email ...",13,790724,web,hacked,NaN,790724,4000
235,Snapchat,NaN,Apr. Indian hackers apparently leaked data the...,13,1700000,app,hacked,NaN,1700000,1
236,Bell,NaN,Somebody claiming to be behind the attack has ...,13,1900000,telecoms,hacked,NaN,1900000,1
237,Cellebrite,NaN,Cellebrite's main product is a device that rip...,13,3000000,tech,hacked,y,3000000,20
238,Clinton campaign,NaN,NaN,13,5000000,government,hacked,NaN,5000000,20
239,ClixSense,NaN,Sept. The information stolen contains username...,13,6600000,web,hacked,NaN,6600000,50000
240,Lynda.com,owned by LinkedIn,Hackers breached a database that held records ...,13,9500000,web,hacked,NaN,9500000,1
241,Interpark,NaN,July. South Korean police are blaming North Ko...,13,10000000,web,hacked,NaN,10000000,20
242,Zomato,Restaurants & events,The hacker is selling the stolen dataset for a...,13,17000000,web,hacked,NaN,17000000,4000
243,Yahoo,NaN,User accounts have been hacked using forged co...,13,32000000,web,hacked,NaN,32000000,4000
244,Weebly,NaN,"Feb. Usernames, passwords and IP addresses sto...",13,43000000,web,hacked,NaN,43000000,4000
245,Dailymotion,video sharing site,"85.2m email addresses extracted, but only 18.3...",13,85200000,web,hacked,NaN,85200000,1
246,Friend Finder Network,"Parent company of Adult Friend Finder , Cams.c...","Usernames, email addresses, passwords for site...",13,412000000,web,hacked,NaN,412000000,1
247,River City Media,Spam operator,A dodgy backup has allegedly resulted in over ...,13,1370000000,web,accidentally published,NaN,700000000,20
248,Telegram,Instant messaging service,"Despite Telegram's claims of super security, t...",13,15000000,tech,hacked,NaN,15000000,1
249,Waterly,App for paying water bills,Jan 2017. Israel-based app contained a vulnera...,14,1000000,app,poor security,NaN,1000000,300
250,CEX,NaN,A misconfigured spambot leaked full contact in...,14,2000000,retail,accidentally published,NaN,2000000,300
251,Swedish Transport Agency,NaN,Information about all vehicles in the country ...,14,3000000,government,poor security,y,3000000,50000
252,Instagram,NaN,A bug exposed user's contact information. Inst...,14,6000000,web,hacked,NaN,6000000,1
253,Equifax,NaN,"If you have a credit report, there’s a good ch...",14,143000000,financial,hacked,y,143000000,50000
254,Spambot,NaN,A misconfigured spambot has leaked over 7m rec...,14,711000000,web,poor security,NaN,711000000,4000

Change the year to actual years

In [ ]:
df.loc[df['YEAR'] =='0', 'YEAR'] = 2004
df.loc[df['YEAR'] =='1', 'YEAR'] = 2005
df.loc[df['YEAR'] =='2', 'YEAR'] = 2006
df.loc[df['YEAR'] =='3', 'YEAR'] = 2007
df.loc[df['YEAR'] =='4', 'YEAR'] = 2008
df.loc[df['YEAR'] =='5', 'YEAR'] = 2009
df.loc[df['YEAR'] =='6', 'YEAR'] = 2010
df.loc[df['YEAR'] =='7', 'YEAR'] = 2011
df.loc[df['YEAR'] =='8', 'YEAR'] = 2012
df.loc[df['YEAR'] =='9', 'YEAR'] = 2013
df.loc[df['YEAR'] =='10', 'YEAR'] = 2014
df.loc[df['YEAR'] =='11', 'YEAR'] = 2015
df.loc[df['YEAR'] =='12', 'YEAR'] = 2016
df.loc[df['YEAR'] =='13', 'YEAR'] = 2017
df.loc[df['YEAR'] =='14', 'YEAR'] = 2017

In [45]:
df

,Entity,alternative name,story,YEAR,records lost,ORGANISATION,METHOD OF LEAK,interesting story,NO OF RECORDS STOLEN,DATA SENSITIVITY
2,AOL,American Online,A former America Online software engineer stol...,2004,92000000,web,inside job,NaN,92000000,1
3,Automatic Data Processing,"Business outsourcing, payrolls, benefits",NaN,2005,125000,financial,poor security,NaN,130000,20
4,Ameritrade Inc.,Computer backup tape containing personal infor...,online broker,2005,200000,financial,lost / stolen device,NaN,200000,20
5,Citigroup,NaN,Blame the messenger! A box of computer tapes c...,2005,3900000,financial,lost / stolen device,y,3900000,300
6,Cardsystems Solutions Inc.,"Third-party payment processor for Visa, Master...",CardSystems was fingered by MasterCard after i...,2005,40000000,financial,hacked,y,40000000,300
7,Hewlett Packard,NaN,Laptop lost/stolen containing employee data: n...,2006,200000,"tech, retail",lost / stolen device,y,200000,20
8,Countrywide Financial Corp,Mortgage financer,NaN,2006,2600000,financial,inside job,NaN,2600000,300
9,KDDI,Japanese telecommunications operator,"Press report: ""Tokyo police have arrested two ...",2006,4000000,telecoms,hacked,y,4000000,1
10,"T-Mobile, Deutsche Telecom",NaN,Thieves got their hands on a storage device wi...,2006,17000000,telecoms,lost / stolen device,NaN,17000000,1
11,AOL,American Online,Durp. AOL VOLUNTARILY released search data for...,2006,20000000,web,accidentally published,y,20000000,1
12,US Dept of Vet Affairs,NaN,The Veterans Affairs Department agreed to pay ...,2006,26500000,"government, military",lost / stolen device,NaN,26500000,20
13,Texas Lottery,NaN,"Data on more than 89,000 lottery winners (incl...",2007,89000,government,inside job,NaN,90000,20
14,City and Hackney Teaching Primary Care Trust,NaN,Heavily encrypted disks containing details of ...,2007,160000,government,lost / stolen device,NaN,160000,20
15,Gap Inc,NaN,Stolen laptop which contained social security ...,2007,800000,retail,lost / stolen device,NaN,800000,20
16,Compass Bank,NaN,A former employee stole a hardrive containing ...,2007,1000000,financial,inside job,y,1000000,300
17,Monster.com,Jobs website,A trojan virus stole log-ins that were used to...,2007,1600000,web,hacked,y,1600000,20
18,Driving Standards Agency,NaN,Hard disk with details of candidates for the d...,2007,3000000,government,lost / stolen device,NaN,3000000,20
19,"Driving Standards Agency,",Details of candidates for the driving theory t...,NaN,2007,3000000,government,lost / stolen device,NaN,3000000,20
20,Hannaford Brothers Supermarket Chain,"Delhaize Group: Hannaford Bros, Sweetbay, Food...",An estimated 4.2 million credit and debit card...,2007,4200000,retail,hacked,NaN,4200000,300
21,TD Ameritrade,US online broker,TD Ameritrade settled a class action lawsuit t...,2007,6300000,financial,hacked,NaN,6300000,1
22,Fidelity National Information Services,Employee sold customer information to a data b...,NaN,2007,8500000,financial,inside job,NaN,8500000,300
23,Dai Nippon Printing,Japanese printing company,A former contractor of Dai Nippon Printing Com...,2007,8637405,retail,inside job,NaN,8600000,1
24,UK Revenue & Customs,HMRC,A set of discs containing confidential details...,2007,25000000,government,lost / stolen device,NaN,25000000,1
25,TK / TJ Maxx,Largest retail breach to date,Hackers hacked a Minnesota store wifi network ...,2007,94000000,retail,hacked,NaN,94000000,300
26,Service Personnel and Veterans Agency (UK),NaN,Stolen USBs containing personal information ab...,2008,50500,government,lost / stolen device,NaN,50000,20
27,Stanford University,NaN,Tens of thousands of past and current Stanford...,2008,72000,academic,lost / stolen device,NaN,72000,20
28,UK Home Office,NaN,PA Consulting lost an unencrypted memory stick...,2008,84000,government,lost / stolen device,NaN,84000,20
29,AT&T,NaN,A laptop was stolen from a car containing unen...,2008,113000,telecoms,lost / stolen device,y,100000,1
30,Starbucks,NaN,A laptop was stolen that contained private inf...,2008,97000,retail,lost / stolen device,y,100000,20
31,RBS Worldpay,the U.S. payment processing arm of The Royal B...,The hack primarily effected U.S. prepaid and t...,2008,1500000,financial,hacked,NaN,1500000,20
...,...,...,...,...,...,...,...,...,...,...
225,uTorrent,NaN,"It's unclear what data has been breached, exac...",2016,35000,web,hacked,NaN,35000,1
226,Banner Health,NaN,Hackers gained access to payment card data via...,2016,3700000,healthcare,hacked,NaN,3700000,300
227,Privatization Agency of the Republic of Serbia,NaN,A text file with personal data and financial d...,2016,5190396,government,accidentally published,NaN,519396,20
228,Quest Diagnostics,NaN,"Nov. The stolen data contained names, DOBs, la...",2017,34000,healthcare,hacked,NaN,34000,4000
229,Three,Three mobile company in the UK,Hackers broke into Three's customer database w...,2017,200000,telecoms,hacked,NaN,200000,20
230,Wonga,NaN,Apr. Customers from the UK and Poland look to ...,2017,270000,financial,hacked,NaN,270000,50000
231,PayAsUGym,NaN,Dec. Fitness website hacked & email address pu...,2017,300000,web,hacked,NaN,300000,1
232,Red Cross Blood Service,NaN,Info leaked includes data about 'at risk sexua...,2017,550000,healthcare,accidentally published,NaN,550000,4000
233,DaFont,Font sharing site,May. Apparently the hacker found out others we...,2017,700000,web,hacked,NaN,700000,4000
234,Brazzers,Porn site,"Sept. 'The data contains 790,724 unique email ...",2017,790724,web,hacked,NaN,790724,4000
235,Snapchat,NaN,Apr. Indian hackers apparently leaked data the...,2017,1700000,app,hacked,NaN,1700000,1
236,Bell,NaN,Somebody claiming to be behind the attack has ...,2017,1900000,telecoms,hacked,NaN,1900000,1
237,Cellebrite,NaN,Cellebrite's main product is a device that rip...,2017,3000000,tech,hacked,y,3000000,20
238,Clinton campaign,NaN,NaN,2017,5000000,government,hacked,NaN,5000000,20
239,ClixSense,NaN,Sept. The information stolen contains username...,2017,6600000,web,hacked,NaN,6600000,50000
240,Lynda.com,owned by LinkedIn,Hackers breached a database that held records ...,2017,9500000,web,hacked,NaN,9500000,1
241,Interpark,NaN,July. South Korean police are blaming North Ko...,2017,10000000,web,hacked,NaN,10000000,20
242,Zomato,Restaurants & events,The hacker is selling the stolen dataset for a...,2017,17000000,web,hacked,NaN,17000000,4000
243,Yahoo,NaN,User accounts have been hacked using forged co...,2017,32000000,web,hacked,NaN,32000000,4000
244,Weebly,NaN,"Feb. Usernames, passwords and IP addresses sto...",2017,43000000,web,hacked,NaN,43000000,4000
245,Dailymotion,video sharing site,"85.2m email addresses extracted, but only 18.3...",2017,85200000,web,hacked,NaN,85200000,1
246,Friend Finder Network,"Parent company of Adult Friend Finder , Cams.c...","Usernames, email addresses, passwords for site...",2017,412000000,web,hacked,NaN,412000000,1
247,River City Media,Spam operator,A dodgy backup has allegedly resulted in over ...,2017,1370000000,web,accidentally published,NaN,700000000,20
248,Telegram,Instant messaging service,"Despite Telegram's claims of super security, t...",2017,15000000,tech,hacked,NaN,15000000,1
249,Waterly,App for paying water bills,Jan 2017. Israel-based app contained a vulnera...,2017,1000000,app,poor security,NaN,1000000,300
250,CEX,NaN,A misconfigured spambot leaked full contact in...,2017,2000000,retail,accidentally published,NaN,2000000,300
251,Swedish Transport Agency,NaN,Information about all vehicles in the country ...,2017,3000000,government,poor security,y,3000000,50000
252,Instagram,NaN,A bug exposed user's contact information. Inst...,2017,6000000,web,hacked,NaN,6000000,1
253,Equifax,NaN,"If you have a credit report, there’s a good ch...",2017,143000000,financial,hacked,y,143000000,50000
254,Spambot,NaN,A misconfigured spambot has leaked over 7m rec...,2017,711000000,web,poor security,NaN,711000000,4000

In [ ]:
np.where(df['records lost'].isnull())[0]

In [46]:
len(np.where(df['records lost'].isnull())[0])

2

In [47]:
np.where(df['records lost'].isnull())[0]

array([146, 162])

In [48]:
len(np.where(df['ORGANISATION'].isnull())[0])

0

In [49]:
len(np.where(df['METHOD OF LEAK'].isnull())[0])

0

In [98]:
df.drop(['interesting story'], axis =1,inplace=True)

In [99]:
df.columns

Index(['Entity', 'alternative name', 'story', 'YEAR', 'records lost',
       'ORGANISATION', 'METHOD OF LEAK', 'NO OF RECORDS STOLEN',
       'DATA SENSITIVITY'],
      dtype='object')

In [100]:
df.head()

,Entity,alternative name,story,YEAR,records lost,ORGANISATION,METHOD OF LEAK,NO OF RECORDS STOLEN,DATA SENSITIVITY
1,NaN,NaN,Elaboration if there's an interesting story or...,"years are encoded (0=2004, 8 = 2012, 9 = 2013,...","(use 3m, 4m, 5m or 10m to approximate unknown ...",NaN,NaN,"(use 3m, 4m, 5m or 10m to approximate unknown ...",1. Just email address/Online information 20 SS...
2,AOL,American Online,A former America Online software engineer stol...,2004,92000000,web,inside job,92000000,1
3,Automatic Data Processing,"Business outsourcing, payrolls, benefits",NaN,2005,125000,financial,poor security,130000,20
4,Ameritrade Inc.,Computer backup tape containing personal infor...,online broker,2005,200000,financial,lost / stolen device,200000,20
5,Citigroup,NaN,Blame the messenger! A box of computer tapes c...,2005,3900000,financial,lost / stolen device,3900000,300

In [55]:
len(np.where(df['DATA SENSITIVITY'].isnull())[0])

0

In [56]:
len(np.where(df['story'].isnull())[0])

36

In [101]:
df

,Entity,alternative name,story,YEAR,records lost,ORGANISATION,METHOD OF LEAK,NO OF RECORDS STOLEN,DATA SENSITIVITY
1,NaN,NaN,Elaboration if there's an interesting story or...,"years are encoded (0=2004, 8 = 2012, 9 = 2013,...","(use 3m, 4m, 5m or 10m to approximate unknown ...",NaN,NaN,"(use 3m, 4m, 5m or 10m to approximate unknown ...",1. Just email address/Online information 20 SS...
2,AOL,American Online,A former America Online software engineer stol...,2004,92000000,web,inside job,92000000,1
3,Automatic Data Processing,"Business outsourcing, payrolls, benefits",NaN,2005,125000,financial,poor security,130000,20
4,Ameritrade Inc.,Computer backup tape containing personal infor...,online broker,2005,200000,financial,lost / stolen device,200000,20
5,Citigroup,NaN,Blame the messenger! A box of computer tapes c...,2005,3900000,financial,lost / stolen device,3900000,300
6,Cardsystems Solutions Inc.,"Third-party payment processor for Visa, Master...",CardSystems was fingered by MasterCard after i...,2005,40000000,financial,hacked,40000000,300
7,Hewlett Packard,NaN,Laptop lost/stolen containing employee data: n...,2006,200000,"tech, retail",lost / stolen device,200000,20
8,Countrywide Financial Corp,Mortgage financer,NaN,2006,2600000,financial,inside job,2600000,300
9,KDDI,Japanese telecommunications operator,"Press report: ""Tokyo police have arrested two ...",2006,4000000,telecoms,hacked,4000000,1
10,"T-Mobile, Deutsche Telecom",NaN,Thieves got their hands on a storage device wi...,2006,17000000,telecoms,lost / stolen device,17000000,1
11,AOL,American Online,Durp. AOL VOLUNTARILY released search data for...,2006,20000000,web,accidentally published,20000000,1
12,US Dept of Vet Affairs,NaN,The Veterans Affairs Department agreed to pay ...,2006,26500000,"government, military",lost / stolen device,26500000,20
13,Texas Lottery,NaN,"Data on more than 89,000 lottery winners (incl...",2007,89000,government,inside job,90000,20
14,City and Hackney Teaching Primary Care Trust,NaN,Heavily encrypted disks containing details of ...,2007,160000,government,lost / stolen device,160000,20
15,Gap Inc,NaN,Stolen laptop which contained social security ...,2007,800000,retail,lost / stolen device,800000,20
16,Compass Bank,NaN,A former employee stole a hardrive containing ...,2007,1000000,financial,inside job,1000000,300
17,Monster.com,Jobs website,A trojan virus stole log-ins that were used to...,2007,1600000,web,hacked,1600000,20
18,Driving Standards Agency,NaN,Hard disk with details of candidates for the d...,2007,3000000,government,lost / stolen device,3000000,20
19,"Driving Standards Agency,",Details of candidates for the driving theory t...,NaN,2007,3000000,government,lost / stolen device,3000000,20
20,Hannaford Brothers Supermarket Chain,"Delhaize Group: Hannaford Bros, Sweetbay, Food...",An estimated 4.2 million credit and debit card...,2007,4200000,retail,hacked,4200000,300
21,TD Ameritrade,US online broker,TD Ameritrade settled a class action lawsuit t...,2007,6300000,financial,hacked,6300000,1
22,Fidelity National Information Services,Employee sold customer information to a data b...,NaN,2007,8500000,financial,inside job,8500000,300
23,Dai Nippon Printing,Japanese printing company,A former contractor of Dai Nippon Printing Com...,2007,8637405,retail,inside job,8600000,1
24,UK Revenue & Customs,HMRC,A set of discs containing confidential details...,2007,25000000,government,lost / stolen device,25000000,1
25,TK / TJ Maxx,Largest retail breach to date,Hackers hacked a Minnesota store wifi network ...,2007,94000000,retail,hacked,94000000,300
26,Service Personnel and Veterans Agency (UK),NaN,Stolen USBs containing personal information ab...,2008,50500,government,lost / stolen device,50000,20
27,Stanford University,NaN,Tens of thousands of past and current Stanford...,2008,72000,academic,lost / stolen device,72000,20
28,UK Home Office,NaN,PA Consulting lost an unencrypted memory stick...,2008,84000,government,lost / stolen device,84000,20
29,AT&T,NaN,A laptop was stolen from a car containing unen...,2008,113000,telecoms,lost / stolen device,100000,1
30,Starbucks,NaN,A laptop was stolen that contained private inf...,2008,97000,retail,lost / stolen device,100000,20
...,...,...,...,...,...,...,...,...,...
225,uTorrent,NaN,"It's unclear what data has been breached, exac...",2016,35000,web,hacked,35000,1
226,Banner Health,NaN,Hackers gained access to payment card data via...,2016,3700000,healthcare,hacked,3700000,300
227,Privatization Agency of the Republic of Serbia,NaN,A text file with personal data and financial d...,2016,5190396,government,accidentally published,519396,20
228,Quest Diagnostics,NaN,"Nov. The stolen data contained names, DOBs, la...",2017,34000,healthcare,hacked,34000,4000
229,Three,Three mobile company in the UK,Hackers broke into Three's customer database w...,2017,200000,telecoms,hacked,200000,20
230,Wonga,NaN,Apr. Customers from the UK and Poland look to ...,2017,270000,financial,hacked,270000,50000
231,PayAsUGym,NaN,Dec. Fitness website hacked & email address pu...,2017,300000,web,hacked,300000,1
232,Red Cross Blood Service,NaN,Info leaked includes data about 'at risk sexua...,2017,550000,healthcare,accidentally published,550000,4000
233,DaFont,Font sharing site,May. Apparently the hacker found out others we...,2017,700000,web,hacked,700000,4000
234,Brazzers,Porn site,"Sept. 'The data contains 790,724 unique email ...",2017,790724,web,hacked,790724,4000
235,Snapchat,NaN,Apr. Indian hackers apparently leaked data the...,2017,1700000,app,hacked,1700000,1
236,Bell,NaN,Somebody claiming to be behind the attack has ...,2017,1900000,telecoms,hacked,1900000,1
237,Cellebrite,NaN,Cellebrite's main product is a device that rip...,2017,3000000,tech,hacked,3000000,20
238,Clinton campaign,NaN,NaN,2017,5000000,government,hacked,5000000,20
239,ClixSense,NaN,Sept. The information stolen contains username...,2017,6600000,web,hacked,6600000,50000
240,Lynda.com,owned by LinkedIn,Hackers breached a database that held records ...,2017,9500000,web,hacked,9500000,1
241,Interpark,NaN,July. South Korean police are blaming North Ko...,2017,10000000,web,hacked,10000000,20
242,Zomato,Restaurants & events,The hacker is selling the stolen dataset for a...,2017,17000000,web,hacked,17000000,4000
243,Yahoo,NaN,User accounts have been hacked using forged co...,2017,32000000,web,hacked,32000000,4000
244,Weebly,NaN,"Feb. Usernames, passwords and IP addresses sto...",2017,43000000,web,hacked,43000000,4000
245,Dailymotion,video sharing site,"85.2m email addresses extracted, but only 18.3...",2017,85200000,web,hacked,85200000,1
246,Friend Finder Network,"Parent company of Adult Friend Finder , Cams.c...","Usernames, email addresses, passwords for site...",2017,412000000,web,hacked,412000000,1
247,River City Media,Spam operator,A dodgy backup has allegedly resulted in over ...,2017,1370000000,web,accidentally published,700000000,20
248,Telegram,Instant messaging service,"Despite Telegram's claims of super security, t...",2017,15000000,tech,hacked,15000000,1
249,Waterly,App for paying water bills,Jan 2017. Israel-based app contained a vulnera...,2017,1000000,app,poor security,1000000,300
250,CEX,NaN,A misconfigured spambot leaked full contact in...,2017,2000000,retail,accidentally published,2000000,300
251,Swedish Transport Agency,NaN,Information about all vehicles in the country ...,2017,3000000,government,poor security,3000000,50000
252,Instagram,NaN,A bug exposed user's contact information. Inst...,2017,6000000,web,hacked,6000000,1
253,Equifax,NaN,"If you have a credit report, there’s a good ch...",2017,143000000,financial,hacked,143000000,50000
254,Spambot,NaN,A misconfigured spambot has leaked over 7m rec...,2017,711000000,web,poor security,711000000,4000

In [ ]:
Imoprt the excel file

In [103]:
df.to_csv('/Users/rosenrot/Downloads/Information1.csv')